package io.github.tmcreative1.playwright.remote.core.enums

enum class EventType {
    CLOSE,
    CONSOLE,
    CRASH,
    DIALOG,
    DOMCONTENTLOADED,
    DOWNLOAD,
    DISCONNECTED,
    FILECHOOSER,
    FRAMEATTACHED,
    FRAMEDETACHED,
    FRAMENAVIGATED,
    FRAMERECEIVED,
    FRAMESENT,
    LOAD,
    PAGE,
    PAGEERROR,
    POPUP,
    REQUEST,
    REQUESTFAILED,
    REQUESTFINISHED,
    RESPONSE,
    SOCKETERROR,
    WEBSOCKET,
    WORKER
}